### ISSUE TITLE
Document links

### ISSUE THREAD

**Issue by yakir12** [jeetsukumaran/DendroPy.jl#2]
The links to the documents do not work.

**Comment by mmore500** [comment]
Thanks for reporting!

It looks like the CI is pushing the to the `gh-pages` branch, but that isn't deploying to github pages. @jeetsukumaran could you toggle the github pages on in the settings for this repository? Here's how I have it configured in my fork:
![image](https://github.com/user-attachments/assets/07943f8f-a0e3-4650-ae54-6db522b739aa)

Here's what's present on the gh-pages branch: https://mmore500.com/DendroPy.jl/dev/
(currently, looks like blank boilerplate)

For now, I'll comment out the docs links in the README until docs content is fixed up. Thanks fore reporting @yakir12!

**Comment by jeetsukumaran** [comment]
Ok, done
